name: Deploy to documentation

on:
  push:
    branches:    
      - master  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Node
      uses: actions/setup-node@v1
    - name: Install dependencies
      run: |
        npm init -y
        npm install -g jsdoc
    - name: Build documentation
      run: |
        jsdoc -c jsdoc_conf.json --verbose
    - name: Deploy documentation
      uses: SamKirkland/FTP-Deploy-Action@2.0.0
      env:
        FTP_SERVER: lava.metanet.ch
        FTP_USERNAME: docs
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        LOCAL_DIR: out
        REMOTE_DIR: api_reference/js
        ARGS: --delete
